import { NextResponse } from "next/server";
import { v2 as cloudinary } from "cloudinary";

// Configure Cloudinary
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

export async function POST(req: Request) {
  try {
    const { reportContent, title, studentName, studentId, prodi, departemen, institusi } = await req.json();

    if (!reportContent || !title) {
      return NextResponse.json(
        { success: false, error: "Report content and title required" },
        { status: 400 }
      );
    }

    // Create HTML content with better styling for image export
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>${title}</title>
    <style>
        body {
            font-family: 'Times New Roman', serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px;
            background: white;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 2px solid #333;
        }
        .header h1 {
            font-size: 24px;
            margin: 10px 0;
            text-transform: uppercase;
        }
        .header p {
            margin: 5px 0;
            font-size: 14px;
        }
        .content {
            white-space: pre-wrap;
            text-align: justify;
        }
        .content h1, .content h2, .content h3 {
            color: #333;
            margin-top: 30px;
            margin-bottom: 15px;
        }
        .content h1 {
            font-size: 20px;
            border-bottom: 1px solid #333;
            padding-bottom: 10px;
        }
        .content h2 {
            font-size: 18px;
        }
        .content h3 {
            font-size: 16px;
        }
        .content pre {
            background: #f5f5f5;
            border: 1px solid #ddd;
            border-left: 4px solid #333;
            padding: 15px;
            margin: 15px 0;
            overflow-x: auto;
            font-family: 'Courier New', monospace;
            font-size: 12px;
        }
        .content code {
            background: #f5f5f5;
            padding: 2px 5px;
            font-family: 'Courier New', monospace;
            font-size: 12px;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>LAPORAN PRAKTIKUM</h1>
        <h2>${title}</h2>
        ${studentName && studentId ? `<p><strong>Nama:</strong> ${studentName} | <strong>NRP:</strong> ${studentId}</p>` : ''}
        <p><strong>Tanggal Generate:</strong> ${new Date().toLocaleDateString('id-ID')}</p>
        ${prodi || departemen || institusi ? `
        <div style="margin-top: 20px; font-size: 12px;">
          ${prodi ? `<p><strong>Program Studi:</strong> ${prodi}</p>` : ''}
          ${departemen ? `<p><strong>Departemen:</strong> ${departemen}</p>` : ''}
          ${institusi ? `<p><strong>Institusi:</strong> ${institusi}</p>` : ''}
        </div>` : ''}
    </div>
    <div class="content">
        ${reportContent}
    </div>
    <div class="footer">
        <p>Generated by SmartLabs</p>
        ${institusi ? `<p>${institusi}</p>` : '<p>POLITEKNIK ELEKTRONIKA NEGERI SURABAYA</p>'}
    </div>
</body>
</html>`;

    // Convert HTML to image using Cloudinary's HTML to image transformation
    try {
      const uploadResult = await cloudinary.uploader.upload(
        `data:text/html;base64,${Buffer.from(htmlContent).toString('base64')}`,
        {
          resource_type: "image",
          format: "png",
          width: 800,
          height: 1200,
          quality: "auto",
          fetch_format: "auto",
          folder: "laporan-exports",
          public_id: `laporan-${studentId || 'unknown'}-${Date.now()}`,
          transformation: [
            { width: 800, crop: "scale" },
            { quality: "auto:good" }
          ]
        }
      );

      return NextResponse.json({
        success: true,
        imageUrl: uploadResult.secure_url,
        publicId: uploadResult.public_id,
      });

    } catch (cloudinaryError) {
      console.error("Cloudinary upload error:", cloudinaryError);

      // Fallback: return the HTML for client-side screenshot
      return NextResponse.json({
        success: true,
        fallback: true,
        htmlContent: htmlContent,
        message: "Using fallback method for image generation"
      });
    }

  } catch (error: any) {
    console.error("Export image API error:", error);
    return NextResponse.json(
      {
        success: false,
        error: error.message || "Gagal export gambar"
      },
      { status: 500 }
    );
  }
}